[NayNay] Registration verifying keys being stripped at Keyring
entropyxyz/sdk pull request #353
Opened 2024-05-24 18:27 UTC by rh0delta

- update creation of functional accounts to include existing data
- issue found when trying to view programs for testnet address, verifying keys list was always empty even tho config contained the keys

## Description

## GitHub Issue or Linear Task

## How Has This Been Tested?

2024-05-28 23:36 UTC, mixmix commented
@frankiebee review this please

2024-05-29 06:38 UTC, frankiebee commented on package.json
> +    "buildLocal": "yarn bundle && yarn unlink && yarn link"
can we call this build:link?

2024-05-29 06:38 UTC, frankiebee commented on src/signing/index.ts
>    signer: Signer
i think that maybe we do keyring or signer but not both. Your thoughts?

2024-05-29 06:42 UTC, frankiebee commented
This fixes? 
> issue found when trying to view programs for testnet address, verifying keys list was always empty even tho config contained the keys

you seem to only have only touched the signing file i would imagine the fix would be in sec/programs/index.ts

2024-05-29 14:02 UTC, rh0delta commented on src/signing/index.ts
>    signer: Signer
the signer in this case is coming from the deviceKeys account, we could remove the keyring from here and include the deviceKey signer and the registration signer and just switch between the two, thoughts?

2024-05-29 14:05 UTC, rh0delta commented
> This fixes?
> 
> > issue found when trying to view programs for testnet address, verifying keys list was always empty even tho config contained the keys
> 
> you seem to only have only touched the signing file i would imagine the fix would be in sec/programs/index.ts

the issue wasnt with programs, it was due to the data passed to the keyring from the cli not being persisted to the instantiation of the keyring instance, and so even if the account has verifying keys, according to the Keyring instance generated there were no keys or anything. the fix is in `src/keys/index.ts`. signing was touched because the device keys account had an empty list of verifying keys, so we had to work some magic to use the registration keys

2024-05-30 01:27 UTC, mixmix requested changes
:flamingo: :checkered_flag: 

Looks good. I've pointed at what looks like gotchas to me. Great work adding some tests to keys, that feels really good as a guard-rail to me

2024-05-30 01:27 UTC, mixmix commented on src/keys/index.ts
> +            account = { ...admin, ...accounts[key] }
I don't know what's gonna be pulled in, and what will win?

2024-05-30 01:27 UTC, mixmix commented on src/keys/index.ts
> +        setTimeout(
comment why this is necessary/ needed plz
(I know, but I will also forget!)

2024-05-30 01:27 UTC, mixmix commented on src/keys/index.ts
> +            account = { ...admin, ...accounts[key] }
I am being paranoid. I don't have enough context to know what's going on here. It seems like admin is a special account that's getting special treatment

2024-05-30 01:27 UTC, mixmix commented on src/signing/index.ts
>    signer: Signer
I can't comment on this

2024-05-30 01:27 UTC, mixmix commented on src/signing/index.ts
> +    }
:fire: - if we're not confident this exists (which is what I see when I see `?.` ... then is if there's not a key after this step... probably `throw` and Error ... cos things are really broken?

2024-05-30 01:27 UTC, mixmix commented on tests/end-to-end.test.ts
> +  await emitterTest
:hot_pepper: - I want to see a minimal test about what was in here. Did it actually emit the `fullAccountView` ?

2024-05-30 01:27 UTC, mixmix commented on tests/keys.test.ts
> +  )
NICE!

Do we need a test test check where that `admin` stuff ends up?

2024-05-30 14:51 UTC, rh0delta commented on tests/keys.test.ts
> +  )
not sure if the test for the admin portion is needed right now, this is to ensure that the keys get populated in the registration account attached to the keyring when the keyring is initialized.

2024-05-30 14:52 UTC, rh0delta commented on tests/keys.test.ts
> +  )
we may be able to consider the emitter test frankie set up tests the population of the admin account as well

2024-05-30 14:53 UTC, rh0delta commented on src/signing/index.ts
> +    }
we may be able to remove this as this was quite the hacky workaround. the underlying cause was actually the subscription to the wrong event thus the cli was unable to capture the account updates and update the config. with the fixes we put in place yesterday, i don;t think we need this. another case of coding before understanding the problem 😬

2024-05-30 14:56 UTC, rh0delta commented on src/index.ts
> +    deviceKey.verifyingKeys = [verifyingKey, ...vk]
the order change is to ensure the new verifying key is the first verifying key in the list on the device keys account. this will be the new verifying key used for signing

2024-05-30 14:57 UTC, rh0delta commented on package.json
> +    "build": "tsup",
yeah i agree with you on this, im going to cut a new smaller PR to just address this change and we can get it merged

2024-05-31 18:34 UTC, rh0delta commented on src/signing/index.ts
>    signer: Signer
i think for now we should leave this as-is until we can solidify that registering is working as expected

2024-05-31 18:41 UTC, rh0delta commented
we need to look more into how we are doing the storage for keyrings on the cli

2024-06-02 20:46 UTC, frankiebee commented on src/keys/index.ts
> +    entropyAccount.admin = masterAccountView.registration
Yes it is. in 'getLazyLoadProxy'
thats really just to make things easy to grab for `getAccounts`.  it was a rushed idea probably not necessary

2024-06-02 20:48 UTC, frankiebee commented on src/keys/index.ts
> +    entropyAccount.admin = masterAccountView.registration
it's sole purpose is for this line
`const { debug, seed, type, verifyingKeys } = this.accounts.masterAccountView`
which is mostly irrelevant right now?

2024-06-02 20:58 UTC, frankiebee commented on tests/end-to-end.test.ts
> +  await emitterTest
> Did it actually emit the fullAccountView ?

what test are you expecting to see? the test is inside the listener that promise is repersenting a wide variety of tests written above this line of code

2024-06-02 20:58 UTC, frankiebee commented on tests/end-to-end.test.ts
> +  await emitterTest
i might be misunderstanding what you want

2024-06-02 21:02 UTC, frankiebee approved these changes
I'm going to put my stamp of approval on this for now and get it merged in so a rc can be created for cli. But lets address deeper testing in a separate pr @mixmix

2024-06-02 21:06 UTC, frankiebee commented on src/index.ts
> +    deviceKey.verifyingKeys = [verifyingKey, ...vk]
related to #365

2024-06-02 21:09 UTC, frankiebee commented on tests/end-to-end.test.ts
> +  await emitterTest
related #351

2024-06-02 21:09 UTC, frankiebee commented on tests/end-to-end.test.ts
> +  await emitterTest
resolving this in favor of next pr to come

2024-06-02 21:10 UTC, frankiebee commented on tests/keys.test.ts
> +  )
related #351 
always like more tests

2024-06-02 21:12 UTC, frankiebee approved these changes
Ive commited to the branch some of mixs docs changes! This is good to go!

2024-06-02 21:13 UTC, merged