add tests to test transfer
entropyxyz/sdk pull request #359
Opened 2024-05-29 03:56 UTC by mixmix

This PR is ready to review + go ... there are some questions I left in the code which need attention before merging though

2024-05-29 03:58 UTC, mixmix commented on tests/transfer.test.ts
> +// BigInt(fromAmountAsHex(1000)) ... number => huge_number => hex => BigInt
:fire: in the CLI transfer amount is calculated suuuuper weird.
This is the function used

2024-05-29 04:04 UTC, mixmix commented on tests/transfer.test.ts
> +      // WARN: signAndSend returns a Promise, but unclear when it resolves, and what the function it resolves with is :melt:
difference from CLI

2024-05-29 04:04 UTC, mixmix commented on tests/transfer.test.ts
> +      const sender = charlie.keyring.accounts.registration.pair
this is different from the CLI?

2024-05-29 04:12 UTC, mixmix commented on tests/transfer.test.ts
> +    // expected: 999998765440000000000n
is this txn fee? 
how can we deterministically test?

2024-05-29 14:14 UTC, rh0delta commented on tests/transfer.test.ts
> +      const sender = charlie.keyring.accounts.registration.pair
this has been updated in my signing branch to match what you have in the test

2024-05-29 17:28 UTC, frankiebee commented on tests/end-to-end.test.ts
> +    await entropy.close()
😅 thanks!

2024-05-29 17:44 UTC, frankiebee commented on tests/transfer.test.ts
> +    // expected: 999998765440000000000n
>How fees are calculated
The final fee for a transaction is calculated using the following parameters:
>base fee: This is the minimum amount a user pays for a transaction. It is declared as a base weight in the runtime and converted to a fee using WeightToFee.
weight fee: A fee proportional to the execution time (input and output and computation) that a transaction consumes.
length fee: A fee proportional to the encoded length of the transaction.
tip: An optional tip to increase the priority of the transaction, giving it a higher chance to be included by the transaction queue.
The base fee and proportional weight and length fees constitute the inclusion fee. The inclusion fee is the minimum fee that must be available for a transaction to be included in a block.

2024-05-29 17:44 UTC, frankiebee commented on tests/transfer.test.ts
> +    // expected: 999998765440000000000n
https://docs.substrate.io/build/tx-weights-fees/

this may or may not be help full i dont know the answer off the top of my head but those are the substrate docs

2024-05-29 19:27 UTC, frankiebee requested changes
remove answered questions or get answers for your questions.

2024-05-29 19:29 UTC, frankiebee commented on tests/transfer.test.ts
> +// BigInt(fromAmountAsHex(1000)) ... number => huge_number => hex => BigInt
i believe this is formatting so we can send whole tokens; @rh0delta?

2024-05-29 19:31 UTC, frankiebee commented on tests/transfer.test.ts
> +      // WARN: signAndSend returns a Promise, but unclear when it resolves, and what the function it resolves with is :melt:
i belive that promise resolves a subscription function. look at polkadot js api https://polkadot.js.org/docs/api/start/api.tx

2024-05-29 22:08 UTC, mixmix commented on tests/transfer.test.ts
> +    // expected: 999998765440000000000n
```
inclusion_fee = base_fee + length_fee + [targeted_fee_adjustment * weight_fee];
final_fee = inclusion_fee + tip;
```

okee, but what the numbers? :shrug:

2024-05-29 22:23 UTC, mixmix commented on tests/transfer.test.ts
> +    // expected: 999998765440000000000n
I'll see if i can hard the txn fee and see if deterministic :eyes:

2024-05-30 00:11 UTC, mixmix commented on tests/transfer.test.ts
> +  // WARNING: this fails if amount sent is too small
```suggestion
  const amount = BigInt(123 * 10 ** SUBSTRATE_DECIMALS)
  // WARNING: this fails if amount sent is too small
```

2024-05-30 00:11 UTC, mixmix commented on tests/transfer.test.ts
> +  // WARNING: this fails if amount sent is too small
DO this and youll see it fail

2024-06-04 01:49 UTC, mixmix commented
@frankiebee ready for re-review

2024-06-04 15:21 UTC, rh0delta approved these changes

2024-06-04 19:10 UTC, frankiebee approved these changes
Love tests!

2024-06-04 19:10 UTC, merged