rename hash -> HASHING_ALGORITHM to be more descriptive and use keccac to make it verfiable
entropyxyz/sdk pull request #360
Opened 2024-05-29 18:12 UTC by frankiebee

This pr is so that the cli can verify the signature against the verifying key using keccac.
This is also renames hash to be more understandable `HASHING_ALGORITHM`

2024-05-30 03:24 UTC, mixmix requested changes
Looks good but for one woops?

2024-05-30 03:24 UTC, mixmix commented on src/signing/adapters/base.ts
> +export const HASHING_ALGORITHM = 'sha3'
:heart: :boom:

2024-05-30 03:24 UTC, mixmix commented on src/signing/adapters/types.ts
> +  HASHING_ALGORITHM: string
:fire: - I am pretty sure this is a mistake?
Out lack of testing in this module is _dangerous_

```suggestion
  hash: string
```

2024-05-30 15:06 UTC, rh0delta commented on src/signing/index.ts
> +      hash: adaptersToRun[0].HASHING_ALGORITHM,
why do we want to leave the argument as `hash` and only change the keyword in the adapters?

2024-05-30 19:26 UTC, frankiebee commented on src/signing/adapters/types.ts
> +  HASHING_ALGORITHM: string
tldr; this is a documentation issue not a code one

2024-05-31 18:31 UTC, rh0delta approved these changes

2024-05-31 18:31 UTC, frankiebee commented on src/signing/index.ts
> +      hash: adaptersToRun[0].HASHING_ALGORITHM,
one thing at a time. signing file is protected space

2024-05-31 18:32 UTC, merged