Mixmix/test sign
entropyxyz/sdk pull request #362
Opened 2024-05-30 04:49 UTC by mixmix

write a test to check simple signing

2024-06-03 23:24 UTC, frankiebee commented
Cli is stable now so lets loop back into here this week @mixmix

2024-06-04 01:48 UTC, mixmix commented
@frankiebee this is Ready for Review!

2024-06-05 10:10 UTC, frankiebee requested changes

2024-06-05 10:10 UTC, frankiebee commented on tests/sign.test.ts
> +      order: ['deviceKeyProxy', 'noop'],
noop program is not part of the default register so this is not needed. `deviceKeyProxy` should be the only adapter used sense it's the "default". Not sure what expcted behavior should be here any thoughts?

2024-06-05 22:29 UTC, mixmix commented on tests/sign.test.ts
> +      order: ['deviceKeyProxy', 'noop'],
why does the test pass then?

2024-06-06 04:02 UTC, mixmix commented on tests/sign.test.ts
> +      order: ['deviceKeyProxy', 'noop'],
DONE!

2024-06-06 04:02 UTC, mixmix commented
I assume that generated a notification.... we shall see!

2024-06-10 23:51 UTC, mixmix commented
@frankiebee please review

2024-06-11 18:24 UTC, frankiebee approved these changes
Love having more tests!

2024-06-11 18:24 UTC, merged