[NayNay] Get all programs for an address
entropyxyz/sdk pull request #371
Opened 2024-06-04 03:08 UTC by rh0delta

## Description
- updated programs dev to add new method to fetch all programs for a given ss58 address
- renamed original get method to getProgramInfo
## GitHub Issue or Linear Task
Closes https://github.com/entropyxyz/cli/issues/66
## How Has This Been Tested?
used @JesseAbram address and returned programs attached
`Retrieved program pointers:
[
  '0x53b7dc00f5e4257be89bc2643eddc2c218623b047a2955e02181828efee3767f'
]`

2024-06-05 10:16 UTC, frankiebee requested changes
just a return type prefernce request otherwise looks good

2024-06-05 10:16 UTC, frankiebee commented on src/programs/dev.ts
> +    return programs
```suggestion
    return programs.toHuman()
```

2024-06-06 04:00 UTC, mixmix commented
@rh0delta is this ready for re-review?

2024-06-06 04:03 UTC, rh0delta commented
@mixmix yes it's ready for re-review, sorry thought Frankie was going to merge it in

2024-06-06 17:19 UTC, frankiebee approved these changes
LGTM

2024-06-06 17:19 UTC, merged