Frankie/i#405programs
entropyxyz/sdk pull request #409
Opened 2024-08-05 19:00 UTC by frankiebee

## Related Issue(s)

- Resolves #[issue_number]

## Proposed Changes

- Change 1
- Change 2
- ...

## Testing

- [x] Unit tests added/updated
- [x] Integration tests added/updated

## Screenshots (if applicable)

## Additional Context

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code.
- [ ] I have updated documentation, where necessary.

2024-08-05 19:01 UTC, frankiebee commented
I have read the CLA Document and I hereby sign the CLA

2024-08-06 15:08 UTC, frankiebee commented
DONT merge yet wanted to see CLA bot would rerun after draft

2024-08-20 22:59 UTC, mixmix commented on src/programs/dev.ts
> +  async get (pointer: string): Promise<ProgramInfo> {
NOTE: breaking change

we have changed what `get` does. This is fine, but I wonder if we should add some checking to what's coming in so we don't get tripped up by this change. Example solutions
- change type `string` for `Pointer` ?
- do a quick check to see if it's an `address` coming in `if (pointer.startsWith('0x`)) ...`

2024-08-20 23:23 UTC, mixmix requested changes
Looks good!
Requested changes that I think are important are marked with :fire: 

- [ ] :fire: CHANGELOG needed
- [ ] :fire: put some check in to catch inevitable accidental misuse of new `get
- [ ] :fire: fix failing test

2024-08-20 23:23 UTC, mixmix commented on src/registration/index.ts
> +        return program
I would refactor as `pruneEmptyConfig(programData)`
I like this because it says what it's doing on the tin. Like this I had to read the code and be "what is this doing?" and come to the conclusion myself

2024-08-20 23:23 UTC, mixmix commented on tests/programs-dev.test.ts
> +  )
ASIDE: Is this needed? I thought we set it to be handled in all our functions so you don't need this?

2024-08-20 23:23 UTC, mixmix commented on tests/programs-dev.test.ts
> +    entropy.programs.dev.getByDeployer(charlieStashAddress)
:fire: I'd like you to use an address that's from Entropy/ keyring please.
I know it's likely the same but doing it this way:
- proves you can access the right address
- shows people reading the tests how to find that address

2024-08-20 23:23 UTC, mixmix commented on tests/programs-dev.test.ts
> +  )
```suggestion
  t.deepEqual(
    programsDeployed,
    [newPointer],
    'charlie has 1 program deployed'
  )
```

2024-08-20 23:23 UTC, mixmix commented on tests/programs-dev.test.ts
> +  )
Suggestions:
- I'd call this `noopProgramInfo` to match the types and reinforce that.
- I'd move this to just before the tests for it. I love seeing `query + assertion on results` grouped (personal taste)

Request :fire: 
- I'd like to see the other fields tested
  - do we have any examples of `program_config` we can test / see coming through from a `get`?

2024-08-20 23:23 UTC, mixmix commented on tests/programs-dev.test.ts
> +  // )
TODO
- [ ] get this passing
- [ ] test what happens with `get(newPointer)` after you remove a program
- [ ] test `remove` failing when a program is being used still? (another PR?)

2024-08-21 02:11 UTC, frankiebee commented
> - [ ] :fire: fix failing test

What test is failing?

2024-08-21 04:56 UTC, mixmix commented
The one in this comment - https://github.com/entropyxyz/sdk/pull/409#discussion_r1724086350
it's failing but commented out

2024-08-21 22:48 UTC, frankiebee commented
ahh missed that in the comment.

2024-08-26 17:42 UTC, frankiebee commented on tests/programs-dev.test.ts
> +  // )
lets do these in a separate PR the extrinsic for removal is not failing but still not being removed not sure why. might be something in events? but requires a lot more digging

2024-08-29 02:02 UTC, frankiebee commented on tests/programs-dev.test.ts
> +  )
maybe thats in the cli? thats not here though

2024-09-18 23:19 UTC, frankiebee commented on src/registration/index.ts
> +        return program
i'll break this out to a separate function but will most likley go with something like format over prune

2024-09-23 18:00 UTC, frankiebee commented on tests/programs-dev.test.ts
> +  )
Config is tested for deploy on the noop. It dosent represent anything in the program but the field is tested.

2024-09-23 18:00 UTC, frankiebee commented on tests/programs-dev.test.ts
> +    entropy.programs.dev.getByDeployer(charlieStashAddress)
done

2024-09-23 18:01 UTC, frankiebee commented on tests/programs-dev.test.ts
> +  )
ah it is but wasnt in the test i copied from.

2024-09-24 03:15 UTC, mixmix requested changes
My only :fire: is I'm pretty concerned about giving up on Schema Parsing.

I would probably throw an error, and if you want, attach the data did some out ok to that error?

2024-09-24 03:15 UTC, mixmix commented on tests/programs-dev.test.ts
> +  }
```suggestion
  const configSchema = {
    type: 'object',
    properties: {
      noop_param: { type: 'string' }
    }
  }
  const auxDataSchema = {
    type: 'object',
    properties: {
      noop_param: { type: 'number' }
    }
  }
```

2024-09-24 03:15 UTC, mixmix commented on tests/programs-dev.test.ts
> +  )
:tropical_fish: _style_ - I like the pattern of "read something, then check what was read". 
i.e. read `programsDeployed`, then test it immediately

<details>
<summary>Why</summary>
By keeping these next to each other I find it easier to parse chunks of test. When the parts are spread out and there is an assertion much further down I find myself going "wait what was that ... oh we're checking that thing from up there...sure... wait so what was in between that I've now forgotten?"
</details>

```suggestion
  const programsDeployed = await run(
    'get deployed programs',
    entropy.programs.dev.getByDeployer(entropy.keyring.accounts.programDev.address)
  )
  t.deepEqual(
    programsDeployed,
    [newPointer],
    'charlie has 1 program deployed'
  )
  
  // Helpful error for old usage
  try {
    await entropy.programs.dev.get(entropy.keyring.accounts.programDev.address)
    t.fail('entropy.programs.dev.get(entropy.keyring.accounts.programDev.address) should have failed')
  } catch (e) {
    t.ok(e.message.includes('pointer length is less then or equal to 48. are you using an address?'), 'should error when using an address')
  }

  const noopProgramOnChain = await run(
    'get a specific program',
    entropy.programs.dev.get(newPointer)
  )
```

2024-09-24 19:10 UTC, frankiebee commented on src/programs/dev.ts
> +    const auxiliaryDataSchema = this.#tryParseSchema(programInfo.auxiliaryDataSchema)// Convert hex string to ArrayBuffer
refer to function   `#tryParseSchema`

2024-09-24 19:15 UTC, frankiebee commented on src/programs/dev.ts
> +      if (e.message.includes('is not valid JSON')) return schema
it is possible for this to be anything including not a json this is a danger zone. we cant say with all certainty what thing is stored on chain. if for some reason someone deploys a program and it's a string do you think we should break here even though the program is on chain?

2024-09-24 19:30 UTC, frankiebee commented on src/programs/dev.ts
> +      if (e.message.includes('is not valid JSON')) return schema
if for some reason is a null should we throw?

2024-09-24 19:33 UTC, frankiebee commented on src/programs/dev.ts
> +    const formatedAuxData = JSON.stringify(auxiliaryDataSchema)
> Aside: JSON.stringify is not deterministic

do you mean in the order it is parsed?

2024-09-24 22:52 UTC, mixmix commented on src/programs/dev.ts
> +    const formatedAuxData = JSON.stringify(auxiliaryDataSchema)
? Not `JSON.parse`. No I'm just having scuttlebutt flashbacks to a dragon. The problem there was basically

```js
msgId = hash(JSON.stringify(msgObject))
```
i.e. something important relied on a reproducible hash which depended on a ... not easily reproducible serialization. It's **probably** not relevant here, but wanted to raise it on the off-chance the "pointer" for a program was derived from `hash(bytecode + configSchema + auxDataSchema)`

2024-09-24 22:54 UTC, mixmix commented on src/programs/dev.ts
> +    const formatedAuxData = JSON.stringify(auxiliaryDataSchema)
# :dragon:

2024-09-24 23:01 UTC, mixmix commented on src/programs/dev.ts
> +      if (e.message.includes('is not valid JSON')) return schema
I think it depends on what your definition of a "program" is.
For me I think its:
- the program code
- the programs interface (which is defined by the schema)

We really need to decide as a team if Schema are "nice to have" or "serious part of the interface".
IMO if it's "nice to have" then .... why is it there?

**Example**: I install a program that says "Users can sign Eth transactions". The program has a config I install which says "maxAmount: $100" or something. As a user, I am a monkey and input "maxAmount: '100 dogs'".
The schema is the guard-rail which says "that is junk... I will not let you register this program cos.... which I ... could register that program I just know that it will ALWAYS fail... or give you a bad time. TRY AGAIN"

2024-09-24 23:03 UTC, mixmix commented on src/programs/dev.ts
> +      if (e.message.includes('is not valid JSON')) return schema
If there is no Schema, that's fine. That implies "no restriction".

I'm more concerned about the case which is "borked schema" which leads to ... unintended/ unexpected jank signing.

2024-09-25 04:24 UTC, mixmix commented on src/programs/dev.ts
> +  auxiliaryDataSchema: unknown
This needs more comments on what the heck the type is. Something simple like "hex-encoded JSON Schema"

I'm trying to do something in the CLI and this looseness makes it hard for me to know what to code

2024-10-02 17:20 UTC, frankiebee commented on CHANGELOG.md
> +    - interface name change: `ProgramInfo` -> `ProgramInterface`
we can probably get rid of broke. But i dont want to do that in this PR. 
> I would personally label these in line with Semver
i'm not sure i understand what you mean here. do you mean changing the titles?

2024-10-02 21:29 UTC, frankiebee commented on src/programs/dev.ts
> +      if (e.message.includes('is not valid JSON')) return schema
Not addressing schemas here. lets stick this in this issue: #418

2024-10-02 21:31 UTC, frankiebee commented on src/programs/dev.ts
> +  auxiliaryDataSchema: unknown
part of #418

2024-10-02 22:06 UTC, mixmix approved these changes

2024-10-02 23:33 UTC, merged