[NayNay] Signing Fix: Message too long error
entropyxyz/sdk pull request #412
Opened 2024-08-20 03:54 UTC by rh0delta

## Related Issue(s)

- Resolves #411 

## Proposed Changes

- update picking validators to use BigInt instead of regular parseInt

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [x] Manual testing performed

## Screenshots (if applicable)

<img width="927" alt="Screenshot 2024-08-19 at 11 49 04 PM" src="https://github.com/user-attachments/assets/127ee24c-4024-4c68-8cf9-486ca9f08898">

## Additional Context

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code.
- [ ] I have updated documentation, where necessary.

2024-08-20 21:05 UTC, frankiebee requested changes

2024-08-20 21:05 UTC, frankiebee commented on src/signing/index.ts
> +      const index = Number(BigInt(`0x${sigRequest}`) % BigInt(keyGroup.unwrap().length))
use the add hex prefix function

2024-08-20 21:05 UTC, frankiebee commented
where the tests at?

2024-08-20 21:06 UTC, frankiebee commented on src/signing/index.ts
> +      const index = Number(BigInt(`0x${sigRequest}`) % BigInt(keyGroup.unwrap().length))
or check first to see if it starts with `0x` before adding it

2024-08-20 21:08 UTC, frankiebee commented on src/signing/index.ts
> +      const index = Number(BigInt(`0x${sigRequest}`) % BigInt(keyGroup.unwrap().length))
side note:
```
> [0,2,3][1n]
2
``` 
scary 😬

2024-08-21 16:05 UTC, rh0delta commented
@frankiebee Ive updated the index calc, and added tests. Ready for re-review!

2024-08-21 21:40 UTC, mixmix commented on src/signing/index.ts
> +      }
```suggestion
      const sigToConvert = hexAddPrefix(sigRequest)
```

they wrote it so that you don't need to check, it already does
https://github.com/polkadot-js/common/blob/master/packages/util/src/hex/addPrefix.ts

2024-08-21 21:41 UTC, mixmix commented on src/signing/index.ts
> +import { hexHasPrefix, hexAddPrefix } from '@polkadot/util'
```suggestion
import { hexAddPrefix } from '@polkadot/util'
```

2024-08-21 21:42 UTC, mixmix submitted a review, later dismissed
Nice test! 
:hot_pepper: Did you check to see that it failed before you applied your fix?

Please merge those suggestions which simplify the code then merge PR.

2024-08-26 18:22 UTC, frankiebee approved these changes
woop woop 👍

2024-08-26 18:28 UTC, merged