Frankie/core#v0.3.0.rc 1
entropyxyz/sdk pull request #421
Opened 2024-10-08 20:21 UTC by frankiebee

## Related Issue(s)

- Resolves #[issue_number]

## Proposed Changes

- Change 1
- Change 2
- ...

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed

## Screenshots (if applicable)

## Additional Context

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code.
- [ ] I have updated documentation, where necessary.

2024-10-11 01:45 UTC, mixmix requested changes
This Review:
- :fire: couple gotchas / need change
- :heavy_check_mark: some `console.log` scrubbing
- :warning: a TODO to remember for when `-rc1` is removed
- some style / requests (casual)

2024-10-11 01:45 UTC, mixmix commented on src/signing/index.ts
> +    return sigProof
If you wanna introspect I like

```js
.then(res => {
  console.log('stuff')
  return res
})
```

2024-10-11 01:45 UTC, mixmix commented on src/signing/index.ts
> +    }, [])
could even make it `pickRelayer(validators, signers)`

2024-10-11 01:45 UTC, mixmix commented on tests/four-nodes.test.ts
> +  t.equal(validators.length, 4, 'expecting 4 validators in validator set')
We can do better than this I think. If you sort that list it should be deterministic right?

2024-10-15 19:54 UTC, frankiebee commented on tests/testing-utils/network.ts
> +}
this snuck in from the old branc removing it

2024-10-15 20:04 UTC, frankiebee commented on package.json
> +    "@polkadot/api": "^14.0.1",
yes this was done on purpose. but we are good with it

2024-10-16 00:50 UTC, mixmix commented on src/signing/index.ts
> +      JSON.stringify(payload)
Why do you parse + stringify?
It doesn't make a difference, ... unless you hit a Uint8Array in which case it makes it into an ugly ?

2024-10-16 00:59 UTC, mixmix commented
Testing error:

```bash
     ✔ network up ------------------------------ 31.12s
    ✔ wasm ------------------------------------ 0s
    ✔ admin account should have an address and for now it should match registrations address
    ✔ got right address
    ✔ entropy ready --------------------------- 0.232s

    ✖ jump-start network
    ---------------------
      operator: error
      at: <anonymous> (/home/runner/work/sdk/sdk/tests/testing-utils/index.ts:64:11)
      stack: |-
  Error: jump-start network timed out
  at file:///home/runner/work/sdk/sdk/dev/testing-utils.mjs:82:43
  at new Promise (<anonymous>)
  at jumpStartNetwork (file:///home/runner/work/sdk/sdk/dev/testing-utils.mjs:81:18)
  at Test.<anonymous> (/home/runner/work/sdk/sdk/tests/end-to-end.test.ts:56:35)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


    ✖ register
    -----------
      operator: error
      at: <anonymous> (/home/runner/work/sdk/sdk/tests/testing-utils/index.ts:64:11)
      stack: |-
  Error: registry.JumpStartNotCompleted:
  at <anonymous> (/home/runner/work/sdk/sdk/src/extrinsic/index.ts:59:22)
  at file:///home/runner/work/sdk/sdk/node_modules/@polkadot/api/promise/decorateMethod.js:56:28
  at file:///home/runner/work/sdk/sdk/node_modules/@polkadot/util/nextTick.js:13:13
  ```

2024-10-21 22:03 UTC, frankiebee commented on dev/docker-scripts/four-nodes.yaml
> +    image: entropyxyz/entropy-tss:${ENTROPY_CORE_VERSION:-latest}
this `-latest` came as a suggestion from @vitropy i believe i am hestant to remove this as i want to get the latest build for this version tag that i am asking for

2024-10-21 22:08 UTC, frankiebee commented on tests/end-to-end.test.ts
> +    if (!process.env.DONT_KILL) await spinNetworkDown(networkType).catch((error) =>
done also env is now `ENTROPY_DONT_KILL`

2024-10-21 22:12 UTC, frankiebee commented on tests/four-nodes.test.ts
> +  t.equal(validators.length, 4, 'expecting 4 validators in validator set')
but if the validator list changes then this is a hardcoded value that needs to change.

2024-10-21 22:20 UTC, frankiebee commented on tests/four-nodes.test.ts
> +  const signingGroup = (await run('signingGroup', entropy.substrate.query.stakingExtension.signers())).toHuman()
i dont see it as a "mess" worth fixing. the point of this test is to ensure that the docker script can run and that jump start works. if i was using it in more places i would consider this. but the point of the `.substrate` is to expose the api of polkadotjs or whatever underlying wrapper for the network communication.

2024-10-23 20:20 UTC, frankiebee commented on src/signing/index.ts
> +      JSON.stringify(payload)
fixed thanks @mixmix for the catch 😬

2024-10-23 20:27 UTC, mixmix submitted a review, later dismissed

2024-10-23 20:51 UTC, mixmix commented on package.json
> +    "publish:rc": "yarn burn && yarn build && npm publish --no-tag",
```suggestion
    "publish:rc": "yarn burn && yarn build && npm publish --tag next",
```

https://docs.npmjs.com/cli/v10/commands/npm-publish#tag

2024-10-23 20:58 UTC, merged