boot script
entropyxyz/sdk pull request #429
Opened 2024-11-05 08:18 UTC by frankiebee

This adds a sort of "boot script" to the `dev` dir. It will jump start and deploy and fund faucets
it also fixs a bug with registering where we were getting "stale" events for a previous registration attempt found while writing this script includes this doc add in the `dev/README.md`:

## sdk "boot script"

For convince at [./deploy-faucets.mjs](./deploy-facuets.mjs ) is a script we use to "deploy" and fund the faucets for our entropy network you can refer to this section and the script itself to deploy your own faucets! Here is it running with a dev environment setup from the root of this project:

```bash
dev/bin/spin-up.sh four-nodes
```
I would take a deep breath here to allow for the 4 nodes to connect before running the next command bellow. On that note the deploy faucet script takes 3 arguments as you can see right now this script assumes you know what your doing if you are running it. So not a lot of bells and whitelist here.

the first argument is the `endpoint` to target, the second is the `fundingSeed` and the third `faucetLookUpSeed` 

```bash
node dev/deploy-facuets.mjs ws://127.0.0.1:9944 0x786ad0e2df456fe43dd1f91ebca22e235bc162e0bb8d53c633e8c85b2af68b7a 0x20423b5ff4984bcb8922483c98afb7eaa056c40fc431f8a314211e3d94a4222f

```
this example above should run in a dev enviroment the funding seed is eve and the report looks something like this and will log to your console:

```
{
  'jump start status at start': 'Ready',
  'using faucet program pointer': '0x3a1d45fecdee990925286ccce71f78693ff2bb27eae62adf8cfb7d3d61e142aa',
  'faucet program pointer from deployment': '0x3a1d45fecdee990925286ccce71f78693ff2bb27eae62adf8cfb7d3d61e142aa',
  'faucet config': {
    max_transfer_amount: 20000000000,
    genesis_hash: 'a4b29c6895ae775fd291377fde31882f66244eaecbdc81e017ebb64d13b27b72'
  },
  'initial balance for funding account': 99999880954644628n,
  'initial funding faucet amount': 24999970238661157n,
  'modifiableKeys on chain': [
    '0x03cd98af667e48b4912c66576f5cdf18aee3764c7aad1c40b9c61d5ac012acf1f6',
    '0x0228aba3e529d3b78b0cd7454a5f694eb09a648ec488b0b4b8ce7cd9abedd96c28',
    '0x03b7c87542f57895d37f1a37a3460e27ec74de7216e6ed48609ffd2fac976ea94a'
  ],
  'faucet look up address': '5EqZMUYz7jjaG2baQWJRzUzM7YhBP4E8TAj6GgqDqWdXriTn',
  faucets: [
    {
      vk: '0x03cd98af667e48b4912c66576f5cdf18aee3764c7aad1c40b9c61d5ac012acf1f6',
      address: '5Gm6JA2ikMK1FfNn3MRmUPLWfi4p6eBzcFtKE1dnJvQpJgpg',
      balance: '24,999,970,238,661,157'
    },
    {
      vk: '0x0228aba3e529d3b78b0cd7454a5f694eb09a648ec488b0b4b8ce7cd9abedd96c28',
      address: '5FqourMb6c3z4rogDnaBb36Ku53ndy3eCiSdjRg2TUAztJ3X',
      balance: '24,999,970,238,661,157'
    },
    {
      vk: '0x03b7c87542f57895d37f1a37a3460e27ec74de7216e6ed48609ffd2fac976ea94a',
      address: '5CUQuSMxTzx74Zb8gsDobhaYSte9vt9a3Db5X6oio4X1pSX1',
      balance: '24,999,970,238,661,157'
    }
  ],
  endpoint: 'ws://127.0.0.1:9944'
}
```

2024-11-05 14:12 UTC, rh0delta requested changes

2024-11-05 14:12 UTC, rh0delta commented on dev/deploy-facuets.mjs
> +if (!faucetLookUpSeed) throw new Error('please provide arguments for faucetLookUpSeed')
```suggestion
if (!endpoint || !fundingSeed || !faucetLookUpSeed) throw new Error('endpoint, fundingSeed, and faucetLookupSeed are required arguments')
```

2024-11-05 14:12 UTC, rh0delta commented on dev/deploy-facuets.mjs
> +})
do we only want to log the report on a failed run of the boot script? might be good to log it for successful attempts too no?

2024-11-05 17:54 UTC, frankiebee commented on dev/deploy-facuets.mjs
> +})
it's logged for both

2024-11-05 20:20 UTC, mixmix commented on dev/README.md
> +## sdk "boot script"
Could open this with context like:

---

When a new network of nodes is turned on, we need some actions to be taken before this new Entropy network is ready to use for tests.

1. Give the nodes a moment to establish connections
2. run "jump start", which establishes who the initial signing nodes are (the network automatically "reshares" these roles periodically after jump start)
3. set up faucet program
    - a) deploy faucet program to network
    - b) install the faucet program for some faucet accounts
    - c) fund the faucet accounts

2024-11-05 20:20 UTC, mixmix commented on dev/README.md
> +
```suggestion


When a new network of nodes is turned on, we need some actions to be taken before this new Entropy network is ready to use for tests.

1. Give the nodes a moment to establish connections
2. run "jump start", which establishes who the initial signing nodes are (the network automatically "reshares" these roles periodically after jump start)
3. set up faucet program
    - a) deploy faucet program to network
    - b) install the faucet program for some faucet accounts
    - c) fund the faucet accounts

```

2024-11-05 20:22 UTC, mixmix commented on dev/README.md
> +  'initial balance for funding account': 99999880954644628n,
or just an inline comment here saying what that unit is. This doesn't need to be super pretty, it's diagnostic

2024-11-05 21:31 UTC, mixmix commented on dev/deploy-faucets.mjs
> +const faucetLookUpSeed = process.argv[4]
```suggestion
const [_, __, endpoint, fundingSeed, faucetLookupSeed] = process.argv
```

2024-11-05 21:31 UTC, mixmix commented on dev/deploy-faucets.mjs
> +if (!faucetLookUpSeed) throw new Error('please provide arguments for faucetLookUpSeed')
move these into `checkEndpoint` functions etc

2024-11-05 21:31 UTC, mixmix commented on dev/deploy-faucets.mjs
> +  if (jumpStartStatus === 'Ready') await jumpStartNetwork(moneyBags, true)
Break the steps up a bit more with space + comments?

```suggestion

  // Jump Start
  const jumpStartStatus = (await moneyBags.substrate.query.stakingExtension.jumpStartProgress()).toHuman().jumpStartStatus
  report['jump start status at start'] = jumpStartStatus
  if (jumpStartStatus === 'Ready') await jumpStartNetwork(moneyBags, true)
  
```

2024-11-05 21:31 UTC, mixmix commented on dev/deploy-faucets.mjs
> +  await sendMoney(moneyBags, faucetRing.accounts.registration.address, BigInt(5 * 10 ** 10))
Do we have the `1e10` / `10**10` constant defined anywhere in this Repo
I'd like to see at least at top of file

```
const BITS_PER_TOKEN = 1e10
```

```suggestion
  await sendMoney(moneyBags, faucetRing.accounts.registration.address, BigInt(5 * BITS_PER_TOKEN))
```

2024-11-05 21:31 UTC, mixmix commented on dev/deploy-faucets.mjs
> +const pointer = '0x3a1d45fecdee990925286ccce71f78693ff2bb27eae62adf8cfb7d3d61e142aa'
style: I like these things as CONST so when I see them I know to look at top of file
```suggestion
const FAUCET_COUNT = 3
// change me if you change the schemas!
const POINTER = '0x3a1d45fecdee990925286ccce71f78693ff2bb27eae62adf8cfb7d3d61e142aa'
```

2024-11-05 21:31 UTC, mixmix commented on dev/deploy-faucets.mjs
> +  await sendMoney(moneyBags, faucetRing.accounts.registration.address, BigInt(5 * 10 ** 10))
This number should be related to the `FAUCET_COUNT` ??

2024-11-05 21:31 UTC, mixmix commented on dev/deploy-faucets.mjs
> +  report['modifiableKeys on chain'] = modifiableKeys.toHuman()
```suggestion
  const verifiyingKeys = await moneyBags.substrate.query.registry.modifiableKeys(faucetRing.accounts.registration.address)
  report['verifyingKeys on chain'] = verifyingKeys.toHuman()
  // These should be the same as faucets.map(faucet => faucet['verification key'])
```

2024-11-06 00:43 UTC, rh0delta commented on dev/deploy-faucets.mjs
> +const faucetLookUpSeed = process.argv[4]
not sure if this is a necessary improvement at this moment, we can clean up the code after the initial release, and just push out a minor patch

2024-11-06 00:44 UTC, rh0delta commented on dev/deploy-faucets.mjs
> +const pointer = '0x3a1d45fecdee990925286ccce71f78693ff2bb27eae62adf8cfb7d3d61e142aa'
i don't think style updates are needed right now to get this out the door, we can polish the boot script after the release sicne we don't really have that many devs that are going to be using the script at the moment

2024-11-06 00:45 UTC, rh0delta commented on dev/fun-bucket.mjs
> +const monkeys = ['🙉 - pandemonium', '🙈 - chaos', '🙊 - anarchy', '🐵 - entropy']
great addition

2024-11-06 00:46 UTC, rh0delta commented on src/programs/dev.ts
> +    if (programInfo === null) return null
program info is null if the program doesn't exist, which is still a valid return type so i don;t believe it constitutes an error

2024-11-06 00:48 UTC, rh0delta commented on src/registration/index.ts
> +    const verifyingKey = result.toHuman().event.data[1]
we don't use the address here, not sure if this is a valid updated for now

2024-11-06 00:48 UTC, rh0delta submitted a review, later dismissed

2024-11-06 01:54 UTC, mixmix commented on dev/deploy-faucets.mjs
> +const pointer = '0x3a1d45fecdee990925286ccce71f78693ff2bb27eae62adf8cfb7d3d61e142aa'
falls in category "important but not urgent" - if we align our code styles a little we get faster parsing + code reviews.

2024-11-06 04:34 UTC, frankiebee commented on dev/deploy-faucets.mjs
> +const pointer = '0x3a1d45fecdee990925286ccce71f78693ff2bb27eae62adf8cfb7d3d61e142aa'
yes will do this my side so i can make sure it's every where

2024-11-06 04:39 UTC, frankiebee commented on dev/deploy-faucets.mjs
> +  await sendMoney(moneyBags, faucetRing.accounts.registration.address, BigInt(5 * 10 ** 10))
done

2024-11-06 04:49 UTC, frankiebee commented on dev/faucet_program.wasm
i'm kicking down the road this one

2024-11-06 04:54 UTC, frankiebee commented on src/index.ts
> +    if (params.programModAddress && !isDeployer(params.programModAddress)) {
i did put a change log entry for this

2024-11-06 05:03 UTC, frankiebee commented on src/programs/dev.ts
> +    if (programInfo === null) return null
it's null if it's not on chain

2024-11-06 07:29 UTC, mixmix approved these changes
Looks good to me

2024-11-06 09:28 UTC, merged